#! /bin/bash

notifcation_id="11221"

function get_brightness {
  xbacklight -get | cut -d '.' -f 1
}

function send_notification {
  brightness=$(get_brightness)
  dunstify -r "$notifcation_id" -u low -t 1000 "Brightness: $brightness%"
}

function increase_brightness {
  xbacklight -inc 5
  send_notification
}

function decrease_brightness {
  xbacklight -dec 5
  send_notification
}

if [ "$1" == "--inc" ]; then
	increase_brightness
elif [ "$1" == "--dec" ]; then
	decrease_brightness
fi
