#!/usr/bin/env bash

function get_brightness {
  xbacklight -get | cut -d '.' -f 1
}

function send_notification {
  icon="/usr/share/icons/Papirus-Dark/24x24/actions/audio-volume-high.svg"
  brightness=$(get_brightness)
  # dunstify -i "$icon" -r 5555 -u normal "    $brightness"
  dunstify -r 5555 -u normal "Brightness: $brightness%"
}

case $1 in
  up)
    xbacklight -inc 5
    send_notification
    ;;
  down)
    xbacklight -dec 5
    send_notification
    ;;
esac