#!/usr/bin/env bash

wifiName=$(nmcli connection show --active | sed 's/|/ /' | awk '{print $1, $8}' | sed -n '1!p')
connectedIcon='📶'
disconnectedIcon='❔'

if [ -z "$wifiName" ]
then
	printf " %s \\n" "$disconnectedIcon"
else
	printf " %s %s \\n" "$connectedIcon" "$wifiName"
fi

