#!/bin/sh

dir="$HOME/Pictures/Wallpapers/"

wallpaper="$(ls $dir | rofi -dmenu -p "Wallpapers")"

if [ -z "$wallpaper" ];
then
	notify-send " ♻️ Aborted" "Task aborted."
else
	pass=$(rofi -dmenu -password -i -no-fixed-num-lines -p "Password: " -theme "$HOME/.config/rofi/themes/password.rasi")

	printf "[I] Setting wallpaper.. \\n"
	wal -i $dir$wallpaper -o "feh --bg-fill $dir$wallpaper" -q

	printf "[I] Compiling dwm.. \\n"
	(cd $HOME/dwm && echo "$pass" | sudo -S make clean install>/dev/null)

	printf "[I] Compiling dmenu.. \\n"
	(cd $HOME/dmenu && echo "$pass" | sudo -S make clean install>/dev/null)

	printf "[I] Compiling st.. \\n"
	(cd $HOME/st && echo "$pass" | sudo -S make clean install>/dev/null)

	notify-send " ✅ Successful" "Enjoy your new theme."
fi
