#! /bin/bash

dir="$HOME/Pictures/Wallpapers/"

wallpaper="$(ls $dir | rofi -dmenu -theme "$HOME/.config/rofi/themes/themes.rasi")"

if [[ ! -z "$wallpaper" ]]
then
	pass=$(rofi -dmenu -password -i -no-fixed-num-lines -p "Password: " -theme "$HOME/.config/rofi/themes/password.rasi")
fi

if [[ ! -z "$wallpaper" && ! -z "$pass" ]]
then
	wal -i $dir$wallpaper -n -q
	feh --bg-fill $dir$wallpaper
	
	sed -i '/.*SchemeNorm*./c\   [SchemeNorm] = { sel_bg,     norm_bg,   norm_border }, // unfocused wins' $HOME/.cache/wal/colors-wal-dwm.h
	sed -i '/.*SchemeSel*./c\    [SchemeSel]  = { norm_fg,      norm_bg,    sel_border },  // the focused win' $HOME/.cache/wal/colors-wal-dwm.h

	(cd $HOME/dwm && echo "$pass" | sudo -S make clean install)  &> /dev/null

	notify-send "Successful" "Enjoy your new theme."
fi
